import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "The Omni Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider>
        
        {children}

        </Provider>
        </body>
    </html>
  );
}
